server:
  port: 9200

spring:
  application:
    name: test

  datasource:
    url: jdbc:postgresql://localhost:5434/terpel
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: tpl

  jackson:
    serialization:
      write-dates-as-timestamps: false